# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uploadMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(652, 676)
        MainWindow.resize(940, 676)  # 加宽窗口
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        # 禁用窗口的最大化
        # MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())

        # 改为水平布局
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        # self.verticalLayout.setObjectName("verticalLayout")

        # 选项卡
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")

        # tab1
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_2.adjustSize()  # 保控件和容器的大小被调整为适合其内容的尺寸
        self.formLayoutWidget_2.move(11, 21)  # 调整控件的位置
        # self.formLayoutWidget_2.setGeometry(QtCore.QRect(11, 21, 276, 363))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(7)   # 控件的水平间距
        self.formLayout_2.setVerticalSpacing(11)    # 控件的垂直间距
        self.formLayout_2.setObjectName("formLayout_2")

        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_block = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_block.sizePolicy().hasHeightForWidth())
        self.lineEdit_block.setSizePolicy(sizePolicy)
        self.lineEdit_block.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_block.setObjectName("lineEdit_block")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_block)

        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_platform = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_platform.sizePolicy().hasHeightForWidth())
        self.lineEdit_platform.setSizePolicy(sizePolicy)
        self.lineEdit_platform.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_platform.setObjectName("lineEdit_platform")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_platform)

        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_well = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_well.sizePolicy().hasHeightForWidth())
        self.lineEdit_well.setSizePolicy(sizePolicy)
        self.lineEdit_well.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_well.setObjectName("lineEdit_well")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_well)

        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_frac_num = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_frac_num.sizePolicy().hasHeightForWidth())
        self.lineEdit_frac_num.setSizePolicy(sizePolicy)
        self.lineEdit_frac_num.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_frac_num.setObjectName("lineEdit_frac_num")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_frac_num)

        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_layer = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_layer.sizePolicy().hasHeightForWidth())
        self.lineEdit_layer.setSizePolicy(sizePolicy)
        self.lineEdit_layer.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_layer.setObjectName("lineEdit_layer")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_layer)

        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_period = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_period.sizePolicy().hasHeightForWidth())
        self.lineEdit_period.setSizePolicy(sizePolicy)
        self.lineEdit_period.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_period.setObjectName("lineEdit_period")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_period)

        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboBox_crew = QtWidgets.QComboBox(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_crew.sizePolicy().hasHeightForWidth())
        self.comboBox_crew.setSizePolicy(sizePolicy)
        self.comboBox_crew.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_crew.setObjectName("comboBox_crew")
        self.comboBox_crew.setEditable(True)
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_crew)

        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.comboBox_measuring_truck = QtWidgets.QComboBox(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_measuring_truck.sizePolicy().hasHeightForWidth())
        self.comboBox_measuring_truck.setSizePolicy(sizePolicy)
        self.comboBox_measuring_truck.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_measuring_truck.setObjectName("comboBox_measuring_truck")
        self.comboBox_measuring_truck.setEditable(False)
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_measuring_truck)

        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_ = QtWidgets.QHBoxLayout()
        self.horizontalLayout_.setObjectName("horizontalLayout_")
        # 软件直传
        self.radioButton_indirect_transmission = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.radioButton_indirect_transmission.setChecked(True)
        self.radioButton_indirect_transmission.setObjectName("radioButton_indirect_transmission")
        self.horizontalLayout_.addWidget(self.radioButton_indirect_transmission)
        # 串口转传
        self.radioButton_direct_transmission = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.radioButton_direct_transmission.setObjectName("radioButton_direct_transmission")
        self.horizontalLayout_.addWidget(self.radioButton_direct_transmission)
        self.formLayout_2.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_)

        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.comboBox_device_num = QtWidgets.QComboBox(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_device_num.sizePolicy().hasHeightForWidth())
        self.comboBox_device_num.setSizePolicy(sizePolicy)
        self.comboBox_device_num.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_device_num.setObjectName("comboBox_device_num")
        self.comboBox_device_num.setEditable(True)
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.comboBox_device_num)
        # 井信息弹窗不显示「压裂队」「设备号」字段
        self.label_11.setVisible(False)
        self.comboBox_crew.setVisible(False)
        self.label_14.setVisible(False)
        self.comboBox_device_num.setVisible(False)

        self.pushButton_upload_wellinfo = QtWidgets.QPushButton(self.tab)
        self.pushButton_upload_wellinfo.setGeometry(QtCore.QRect(10, 390, 281, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_upload_wellinfo.sizePolicy().hasHeightForWidth())
        self.pushButton_upload_wellinfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_upload_wellinfo.setFont(font)
        self.pushButton_upload_wellinfo.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_upload_wellinfo.setObjectName("pushButton_upload_wellinfo")



        # tab2
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        # tab3
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        # self.tabWidget.addTab(self.tab_3, "")
        # tab4
        # self.tab_4 = QtWidgets.QWidget()
        # self.tab_4.setObjectName("tab_4")
        # self.tabWidget.addTab(self.tab_4, "")
        # tab5

        # tab6
        # self.tab_6 = QtWidgets.QWidget()
        # self.tab_6.setObjectName("tab_6")
        # self.tabWidget.addTab(self.tab_6, "")

        # self.verticalLayout.addWidget(self.tabWidget)
        # self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        # self.textEdit.setEnabled(True)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        # self.textEdit.setSizePolicy(sizePolicy)
        # self.textEdit.setObjectName("textEdit")
        # self.verticalLayout.addWidget(self.textEdit)
        # self.verticalLayout.setStretch(0, 5)
        # self.verticalLayout.setStretch(1, 1)
        # 右侧的文本编辑框
        # self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        # self.textEdit.setObjectName("textEdit")
        # self.textEdit.setVisible(False)

        # 右侧的垂直布局
        self.verticalLayout_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_right.setObjectName("verticalLayout_right")

        # 第一个GroupBox
        self.groupBox1 = QtWidgets.QGroupBox("井信息状态栏")
        self.textEdit = QtWidgets.QTextEdit()
        self.groupBox1_layout = QtWidgets.QVBoxLayout()
        self.groupBox1_layout.addWidget(self.textEdit)
        self.groupBox1.setLayout(self.groupBox1_layout)

        # 第二个GroupBox
        self.groupBox2 = QtWidgets.QGroupBox("施工秒点数据、液体性能数据")
        self.textEdit2 = QtWidgets.QTextEdit()
        self.groupBox2_layout = QtWidgets.QVBoxLayout()
        self.groupBox2_layout.addWidget(self.textEdit2)
        self.groupBox2.setLayout(self.groupBox2_layout)

        # 第三个GroupBox
        self.groupBox3 = QtWidgets.QGroupBox("黏度数据状态栏")
        self.textEdit3 = QtWidgets.QTextEdit()
        self.groupBox3_layout = QtWidgets.QVBoxLayout()
        self.groupBox3_layout.addWidget(self.textEdit3)
        self.groupBox3.setLayout(self.groupBox3_layout)

        # 黏度数据采集弹窗用：关闭弹窗时把黏度左侧区域和 groupBox3 放回此容器，主窗口不显示
        self.viscosity_dialog_container = QtWidgets.QWidget(MainWindow)
        self.viscosity_dialog_container.setObjectName("viscosity_dialog_container")
        self.viscosity_dialog_container_layout = QtWidgets.QHBoxLayout(self.viscosity_dialog_container)
        self.viscosity_dialog_container_layout.setContentsMargins(0, 0, 0, 0)
        # 秒点数据采集弹窗用：关闭弹窗时把“秒点左侧区域”和“秒点状态栏”放回这个容器，不显示在主窗口
        self.second_point_dialog_container = QtWidgets.QWidget(MainWindow)
        self.second_point_dialog_container.setObjectName("second_point_dialog_container")
        self.second_point_dialog_container_layout = QtWidgets.QHBoxLayout(self.second_point_dialog_container)
        self.second_point_dialog_container_layout.setContentsMargins(0, 0, 0, 0)
        # 下面两行：把 groupBox2 和“秒点左侧区域”先放进容器（秒点左侧区域由 OpenExeWindow 在 init_data 里创建并加到这里）
        # 不在主窗口主布局里 addWidget(second_point_dialog_container)，所以主窗口上看不见这个容器
        self.second_point_dialog_container_layout.addWidget(self.groupBox2, stretch=3)

        # 井信息状态栏移到弹窗，主窗口右侧只保留后两个
        self.well_info_container = QtWidgets.QWidget(MainWindow)
        self.well_info_container.setObjectName("well_info_container")
        self.well_info_container_layout = QtWidgets.QHBoxLayout(self.well_info_container)
        self.well_info_container_layout.setContentsMargins(0, 0, 0, 0)
        self.well_info_container_layout.addWidget(self.tab)  # 井信息表单
        self.well_info_container_layout.addWidget(self.groupBox1)  # 井信息状态栏
        self.well_info_container_layout.setStretch(0, 4)
        self.well_info_container_layout.setStretch(1, 3)
        # 不把 well_info_container 加入主布局，仅用于弹窗复用
        # 将GroupBox添加到右侧垂直布局，并设置拉伸因子（不再添加 groupBox1）


        # 添加控件到布局
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_right)

        # 设置拉伸比例
        self.horizontalLayout.setStretch(0, 4)  # 左侧占3份
        self.horizontalLayout.setStretch(1, 3)  # 右侧占1份

        MainWindow.setCentralWidget(self.centralwidget)

        # 菜单栏、状态栏
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 23))
        self.menubar.setObjectName("menubar")
        # 查看菜单 -> 绘图子菜单
        # self.menu_view = QtWidgets.QMenu(self.menubar)
        # self.menu_view.setObjectName("menu_view")
        # self.action_plot = QtWidgets.QAction(MainWindow)
        # self.action_plot.setObjectName("action_plot")
        # self.menu_view.addAction(self.action_plot)
        # self.menubar.addAction(self.menu_view.menuAction())
        # MainWindow.setMenuBar(self.menubar)

        # 文件
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.action_well_info = QtWidgets.QAction(MainWindow)
        self.action_well_info.setObjectName("action_well_info")
        self.menu_file.addAction(self.action_well_info)
        self.menubar.addAction(self.menu_file.menuAction())
        # 功能
        self.menu_function = QtWidgets.QMenu(self.menubar)
        self.menu_function.setObjectName("menu_function")
        self.action_second_point = QtWidgets.QAction(MainWindow)
        self.action_second_point.setObjectName("action_second_point")
        self.action_viscosity = QtWidgets.QAction(MainWindow)
        self.action_viscosity.setObjectName("action_viscosity")
        self.action_edit_liquid = QtWidgets.QAction(MainWindow)
        self.action_edit_liquid.setObjectName("action_edit_liquid")
        self.menu_function.addAction(self.action_second_point)
        self.menu_function.addAction(self.action_viscosity)
        self.menu_function.addAction(self.action_edit_liquid)
        self.menubar.addAction(self.menu_function.menuAction())
        # 查看
        self.menu_view = QtWidgets.QMenu(self.menubar)
        self.menu_view.setObjectName("menu_view")
        self.action_csv = QtWidgets.QAction(MainWindow)
        self.action_csv.setObjectName("action_csv")
        self.action_plot = QtWidgets.QAction(MainWindow)
        self.action_plot.setObjectName("action_plot")
        self.action_history = QtWidgets.QAction(MainWindow)
        self.action_history.setObjectName("action_history")

        self.menu_view.addAction(self.action_plot)
        self.menu_view.addAction(self.action_history)
        self.menubar.addAction(self.menu_view.menuAction())
        # 帮助
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.menu_help.addAction(self.action_help)
        self.menubar.addAction(self.menu_help.menuAction())
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)

        # 选项卡默认选中
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.label_17.setText(_translate("MainWindow", "串 口 号"))
        self.label_7.setText(_translate("MainWindow", "区    块"))
        self.label_18.setText(_translate("MainWindow", "井    台"))
        self.label_8.setText(_translate("MainWindow", "井    号"))
        self.label_9.setText(_translate("MainWindow", "压裂次数"))
        self.label_12.setText(_translate("MainWindow", "层    位"))
        self.label_10.setText(_translate("MainWindow", "段/级编号 "))
        self.label_11.setText(_translate("MainWindow", "压 裂 队"))
        self.label_16.setText(_translate("MainWindow", "仪表车厂家"))
        self.label_13.setText(_translate("MainWindow", "传输方式"))
        self.radioButton_direct_transmission.setText(_translate("MainWindow", "软件直传"))
        self.radioButton_indirect_transmission.setText(_translate("MainWindow", "串口转传"))
        self.label_14.setText(_translate("MainWindow", "设 备 号"))

        # 单机版：按钮改为“保存井信息”
        self.pushButton_upload_wellinfo.setText(_translate("MainWindow", "保存井信息"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "井信息设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "上传数据"))

        self.groupBox1.setTitle(_translate("MainWindow", "井信息状态栏"))
        self.groupBox2.setTitle(_translate("MainWindow", "施工秒点数据状态栏"))
        self.groupBox3.setTitle(_translate("MainWindow", "粘度数据状态栏"))

        # self.pushButton_start_receive.setText(_translate("MainWindow", "开始接收"))
        # self.pushButton_stop_receive.setText(_translate("MainWindow", "停止接收"))

        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "施工秒点数据、液体性能数据"))
        # 菜单栏文案
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.action_well_info.setText(_translate("MainWindow", "井信息设置"))
        self.menu_function.setTitle(_translate("MainWindow", "功能"))
        self.action_second_point.setText(_translate("MainWindow", "秒点数据采集"))
        self.action_viscosity.setText(_translate("MainWindow", "粘度数据采集"))
        self.action_edit_liquid.setText(_translate("MainWindow", "编辑液体类型"))
        self.menu_view.setTitle(_translate("MainWindow", "查看"))
        self.action_csv.setText(_translate("MainWindow", "csv"))
        self.action_plot.setText(_translate("MainWindow", "实时曲线"))
        self.action_history.setText(_translate("MainWindow", "历史曲线"))
        self.menu_help.setTitle(_translate("MainWindow", "帮助"))
        self.action_help.setText(_translate("MainWindow", "说明"))


# if __name__ == "__main__":
#     import sys
#     try:
#         app = QtWidgets.QApplication(sys.argv)
#         MainWindow = QtWidgets.QMainWindow()
#         ui = Ui_MainWindow()
#         ui.setupUi(MainWindow)
#         MainWindow.show()
#         sys.exit(app.exec_())
#     except Exception as e:
#         print(f"Error: {e}")
